### ISSUE TITLE
чтот не могу войти

### ISSUE THREAD

**Issue by HukakHePak** [Defeatq/chat#1]
ввожу почту, а потом еще раз почту, а потом еще раз почту. в общем циклится на почте

**Comment by Defeatq** [comment]
> ввожу почту, а потом еще раз почту, а потом еще раз почту. в общем циклится на почте

Логично, github pages же тут не работает)

**Comment by HukakHePak** [comment]
аа прости я не сильно умный. просто раз они есть, думал работают.
